zendesk:
  ng:
    sub_domain: "olxng1427922231"
    username: "zendesk@olx.com"
    token: "60yxq6B6ElDPVdbAQINFbitPEVUT1lzZSK1gGmZh"
    brand_id: "350972"
whatsapp:
  ng:
    phone: "5491139258641"
    password: "XAx5truw7eQb44TMCj6EIg42QcQ="
    nickname: "OLX Support"
